### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/path/LT_DSE/RT_MDNet/models/rt-mdnet.pth'

### ISSUE THREAD

**Issue by the-nilosch** [Daikenan/LT_DSE#8]

**Comment by the-nilosch** [comment]
Related, but does not work for me: https://github.com/IlchaeJung/RT-MDNet/issues/25

```
Traceback (most recent call last):
  File "LT_DSE_Demo.py", line 1337, in <module>
    tf.app.run()
  File "/root/miniconda3/envs/LTDSE/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "LT_DSE_Demo.py", line 1334, in main
    eval_tracking('demo', p=p, save=True)
  File "LT_DSE_Demo.py", line 1313, in eval_tracking
    tracker = MobileTracker(image, region, video=video, p=p,groundtruth=groundtruth)
  File "LT_DSE_Demo.py", line 210, in __init__
    self.init_rtmdnet(image, init_gt1)
  File "LT_DSE_Demo.py", line 264, in init_rtmdnet
    self.rtmodel = RTMDNet(rt_opts['model_path'])
  File "/path/LT_DSE/RT_MDNet/rtmdnet_model.py", line 94, in __init__
    self.load_model(model_path)
  File "/path/LT_DSE/RT_MDNet/rtmdnet_model.py", line 142, in load_model
    states = torch.load(model_path)
  File "/root/miniconda3/envs/LTDSE/lib/python3.6/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/crebmann/LT_DSE/RT_MDNet/models/rt-mdnet.pth'
```

**Comment by Daikenan** [comment]
You can download 'rt-mdnet.pth' from [here](https://www.dropbox.com/s/lr8uft05zlo21an/rt-mdnet.pth?dl=0).
