### ISSUE TITLE
Download of Models not successful

### ISSUE THREAD

**Issue by the-nilosch** [Daikenan/LT_DSE#9]
I had to create two folders manually to get (hopefully) all files from `download_models.sh`

```
path/LT_DSE/models
path/LT_DSE/RT_MDNet/models
```

**Comment by the-nilosch** [comment]
It seems that something else is missing...

```
Traceback (most recent call last):
  File "LT_DSE_Demo.py", line 1337, in <module>
    tf.app.run()
  File "/root/miniconda3/envs/LTDSE/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "LT_DSE_Demo.py", line 1334, in main
    eval_tracking('demo', p=p, save=True)
  File "LT_DSE_Demo.py", line 1313, in eval_tracking
    tracker = MobileTracker(image, region, video=video, p=p,groundtruth=groundtruth)
  File "LT_DSE_Demo.py", line 213, in __init__
    self.local_init(image, init_gt1)
  File "LT_DSE_Demo.py", line 792, in local_init
    self.local_Tracker.initialize(image, init_bbox)
  File "/path/LT_DSE/pytracking/tracker/atom/atom.py", line 31, in initialize
    self.initialize_features()
  File "/path/LT_DSE/pytracking/tracker/atom/atom.py", line 19, in initialize_features
    self.params.features.initialize()
  File "/path/LT_DSE/pytracking/features/extractor.py", line 16, in initialize
    f.initialize()
  File "/path/LT_DSE/pytracking/features/deep.py", line 95, in initialize
    self.net, _ = load_network(net_path_full, backbone_pretrained=False)
  File "/path/LT_DSE/ltr/admin/loading.py", line 53, in load_network
    checkpoint_dict = torch_load_legacy(checkpoint_path)
  File "/path/LT_DSE/ltr/admin/loading.py", line 97, in torch_load_legacy
    checkpoint_dict = torch.load(path)
  File "/root/miniconda3/envs/LTDSE/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/root/miniconda3/envs/LTDSE/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
EOFError: Ran out of input
```

**Comment by Daikenan** [comment]
atom_default.pth did not download successfully.You can download it manually(updated in readme). In addition,I have fixed this download script bug, you can also update the code and download models automatically with script.
